apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xidr-agent.fullname" . }}-secrets
  namespace: {{ include "xidr-agent.namespace" . }}
  labels:
    {{- include "xidr-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  XIDR_ORGANIZATION_ID: {{ required "organizationId is required" .Values.organizationId | quote }}
  XIDR_CLUSTER_ID: {{ required "clusterId is required" .Values.clusterId | quote }}
  {{- if .Values.apiToken }}
  XIDR_API_TOKEN: {{ .Values.apiToken | quote }}
  {{- end }}
