{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "xidr-agent.fullname" . }}
  namespace: {{ include "xidr-agent.namespace" . }}
  labels:
    {{- include "xidr-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "xidr-agent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      path: /metrics
{{- end }}
